apiVersion: v1
kind: Pod
metadata:
  name: todolist-java-app
  labels:
    app: todolist
spec:
  containers:
    - name: todolist
      image: pankajdubeycs0056/todolist
      ports:
        - containerPort: 8084
