apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: todolist-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      name: todolist-java-app
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: pankajdubeycs0056/todolist
          ports:
            - containerPort: 8084
